name: Deploy Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-page-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish frontend to page branch
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: page
          folder: frontend
          clean: true
          single-commit: true
