name: Deploy Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
    - cron: "0 14 * * *"

permissions:
  contents: write

jobs:
  build-and-deploy-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: data-cli/go.mod

      - name: Generate latest data
        working-directory: data-cli
        env:
          OSH_GITHUB_TOKEN: ${{ secrets.OSH_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run .

      - name: Publish generated data to data branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: data
          folder: frontend/data
          clean: true
          single-commit: true
